language: ruby
rvm:
  - 2.1.0
env:
  global:
    - JIRA_URL='jira.example.com'
    - JIRA_USERNAME='username'
    - JIRA_PASSWORD='password'
install: ./build.sh
script: rspec
notifications:
  email:
    on_success: never
    on_failure: change
